-- Active: 1736532502233@@127.0.0.1@3306@datag3

-- RETO MYSQL : CREAR 3 TABLAS EN MYSQL RELACIONADAS PARA 
--REGISTRAR LAS DIRECCIONES DE UNA EMPRESA, CREAR TABLA EMPRESA, DIRECCIONES Y CIUDAD 
--POR EJEMPLO LA EMPRESA A TIENE 2 DIRECCIONES EN LA CIUDAD DE AREQUIPA
--SE DEBE REGISTRAR ESOS DATOS EN LA TABAL DE DIRECCIONES, UTILIZAR RELACIONES ENTRE EMPRESA DIRECCIONES Y CIUDAD
create table empresa(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL
)

create table ciudad(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOt NULL
)

create table direccion(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    empresa_id int NOT NULL,
    ciudad_id int NOT NULL,
    Foreign Key (empresa_id) REFERENCES empresa(id),
    Foreign Key (ciudad_id) REFERENCES ciudad(id)
)
